server:
  port: ${PORT:5000}

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:https://api-cloud-config.herokuapp.com
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/user-service
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackUri: forward:/department-service
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: true
      name: application
      profile: prod
      label: master

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

logging:
  level:
    org.springframework.cloud.gateway: TRACE